#pragma once
#include "ParkingLot.h"
#include "Person.h"
#include "PricingStrategy.h"
#include <iostream>
#include <iomanip>
#include <memory>
#include <vector>
#include <map>

// AdminPanel provides facade for admin operations
class AdminPanel {
private:
    ParkingLot* parkingLot;
    std::shared_ptr<Admin> currentAdmin;
    std::map<std::string, std::shared_ptr<Admin>> admins;

public:
    AdminPanel(ParkingLot* lot) : parkingLot(lot), currentAdmin(nullptr) {}

    // Admin authentication
    bool login(std::shared_ptr<Admin> admin) {
        if (!admin || !admin->getIsActive()) {
            std::cout << "❌ Login failed: Invalid or inactive admin account\n";
            return false;
        }
        currentAdmin = admin;
        std::cout << "✅ Admin '" << admin->getName() << "' logged in successfully\n";
        return true;
    }

    void logout() {
        if (currentAdmin) {
            std::cout << "👋 Admin '" << currentAdmin->getName() << "' logged out\n";
            currentAdmin = nullptr;
        }
    }

    // Add a new floor to the parking lot
    bool addParkingFloor(std::shared_ptr<ParkingFloor> floor) {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return false;
        }

        if (!currentAdmin->canAddFloor()) {
            std::cout << "❌ Access denied: Insufficient privileges to add floors\n";
            return false;
        }

        parkingLot->addFloor(floor);
        std::cout << "✅ Floor " << floor->getFloorNumber() << " added successfully by "
                  << currentAdmin->getName() << "\n";
        return true;
    }

    // Update pricing strategy
    bool updatePricingStrategy(std::unique_ptr<PricingStrategy> newStrategy) {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return false;
        }

        if (!currentAdmin->canUpdatePricing()) {
            std::cout << "❌ Access denied: Insufficient privileges to update pricing\n";
            return false;
        }

        // Note: This would require adding a method to ParkingLot to update pricing
        std::cout << "✅ Pricing strategy updated by " << currentAdmin->getName() << "\n";
        return true;
    }

    // Generate occupancy report
    void generateOccupancyReport() {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return;
        }

        if (!currentAdmin->canViewReports()) {
            std::cout << "❌ Access denied: Insufficient privileges to view reports\n";
            return;
        }

        std::cout << "\n╔═══════════════════════════════════════════════════╗\n";
        std::cout << "║         PARKING LOT OCCUPANCY REPORT             ║\n";
        std::cout << "╚═══════════════════════════════════════════════════╝\n";
        std::cout << "Generated by: " << currentAdmin->getName() << " (" 
                  << currentAdmin->getAdminLevel() << ")\n";
        std::cout << "─────────────────────────────────────────────────────\n";
        
        int totalCapacity = parkingLot->getMaxCapacity();
        int currentOccupancy = parkingLot->getCurrentOccupancy();
        int available = totalCapacity - currentOccupancy;
        double occupancyRate = (totalCapacity > 0) ? 
            (currentOccupancy * 100.0 / totalCapacity) : 0.0;

        std::cout << "Total Capacity:     " << std::setw(8) << totalCapacity << " spots\n";
        std::cout << "Current Occupancy:  " << std::setw(8) << currentOccupancy << " vehicles\n";
        std::cout << "Available Spots:    " << std::setw(8) << available << " spots\n";
        std::cout << "Occupancy Rate:     " << std::setw(8) << std::fixed 
                  << std::setprecision(2) << occupancyRate << "%\n";
        
        if (occupancyRate >= 90.0) {
            std::cout << "\n⚠️  WARNING: Parking lot is nearly full!\n";
        } else if (occupancyRate < 50.0) {
            std::cout << "\n✓ Parking lot has ample space available\n";
        }

        std::cout << "═════════════════════════════════════════════════════\n\n";
    }

    // Display all display boards
    void viewAllDisplayBoards() {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return;
        }

        std::cout << "\n🔍 Admin viewing all display boards...\n";
        parkingLot->displayAllBoards();
    }

    // Emergency: Close parking lot
    void emergencyShutdown(const std::string& reason) {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return;
        }

        if (currentAdmin->getAdminLevel() != "SUPER_ADMIN") {
            std::cout << "❌ Access denied: Only SUPER_ADMIN can perform emergency shutdown\n";
            return;
        }

        std::cout << "\n🚨 EMERGENCY SHUTDOWN INITIATED 🚨\n";
        std::cout << "By: " << currentAdmin->getName() << "\n";
        std::cout << "Reason: " << reason << "\n";
        std::cout << "All entry points are now CLOSED\n";
        std::cout << "Existing vehicles can exit normally\n";
    }

    // Register a new admin
    void registerAdmin(std::shared_ptr<Admin> newAdmin) {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return;
        }

        if (currentAdmin->getAdminLevel() != "SUPER_ADMIN") {
            std::cout << "❌ Access denied: Only SUPER_ADMIN can register new admins\n";
            return;
        }

        admins[newAdmin->getId()] = newAdmin;
        std::cout << "✅ New admin '" << newAdmin->getName() << "' registered successfully\n";
    }

    // System statistics
    void displaySystemStats() {
        if (!currentAdmin) {
            std::cout << "❌ Access denied: Please login first\n";
            return;
        }

        std::cout << "\n📊 SYSTEM STATISTICS\n";
        std::cout << "════════════════════════════════════════\n";
        std::cout << "Current Admin: " << currentAdmin->getName() << "\n";
        std::cout << "Admin Level: " << currentAdmin->getAdminLevel() << "\n";
        std::cout << "Total Registered Admins: " << admins.size() << "\n";
        std::cout << "════════════════════════════════════════\n\n";
    }
};
